ALTER TABLE "supplier" DROP CONSTRAINT "FK_f6f7031f59a82e3a3e9e2c4ee6d";
ALTER TABLE "supplier" ALTER COLUMN "addressId" DROP NOT NULL;
ALTER TABLE "supplier" ADD CONSTRAINT "FK_f6f7031f59a82e3a3e9e2c4ee6d" FOREIGN KEY ("addressId") REFERENCES "address"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;
